Feature: integrate dice-group/metall-ffi
dice-group/metall pull request #14
Opened 2023-11-29 10:05 UTC by Clueliss

Integrates [dice-group/metall-ffi](https://github.com/dice-group/metall-ffi)

2023-12-08 14:29 UTC, bigerl requested changes
Thx. Looks good. Only some minor things left.

2023-12-08 14:29 UTC, bigerl commented on libs/ffi/src/dice/ffi/metall.h
> + * @return true on success, false on failure. On failure, sets errno to one of the following values:
return doc is wrong

2023-12-08 14:29 UTC, bigerl commented on libs/ffi/src/dice/ffi/metall.h
> + * @return true on success, false on failure. On failure, sets errno to one of the following values:
return doc is wrong

2023-12-08 14:29 UTC, bigerl commented on libs/ffi/src/dice/ffi/metall.h
> + * @return true on success, false on failure. On failure, sets errno to one of the following values:
return doc is wrong

2023-12-08 14:29 UTC, bigerl commented on libs/ffi/src/dice/ffi/metall.h
> + *      - ENOTRECOVERABLE if the given metall datastore is inconsistent
```suggestion
 *      - ENOTRECOVERABLE if the given metall datastore is inconsistent or already in use
```

2023-12-08 14:29 UTC, bigerl commented on libs/ffi/src/dice/ffi/metall.h
> + *      - ENOTRECOVERABLE if the given metall datastore is inconsistent
```suggestion
 *      - ENOTRECOVERABLE if the given metall datastore is inconsistent or already in use
```

2023-12-08 14:29 UTC, bigerl commented on libs/ffi/src/dice/ffi/metall.cpp
> -void metall_flush() { g_manager->flush(); }
Is there a particular reason why the flush function was dropped?

2023-12-11 14:08 UTC, Clueliss commented on libs/ffi/src/dice/ffi/metall.cpp
> -void metall_flush() { g_manager->flush(); }
No, just never existed in our version of the FFI. Will add it again

2023-12-12 12:14 UTC, bigerl approved these changes

2023-12-12 13:27 UTC, merged